apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wiki-mcp
resources:
  - namespace.yaml
  - harbor-pull-secret.yaml
  - image-updater-rbac.yaml
  - github-token-secret.yaml
  - pvc.yaml
  - git-sync-script.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: harbor.sirddail.net/ai/wiki-mcp
    newTag: 0.1.5
